import Link from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="flex flex-col gap-2 underline text-blue-500">
          <Link href={`/`}>Go home</Link> <br />
          <Link href={`/counter/sub`}>Go to sub</Link> <br />
          <Link href={`/counter/`}>Go to counter home</Link> <br />
        </ul>
        {children}
      </body>
    </html>
  );
}
